#!/bin/sh

msg_info() {
  echo -e "\e[94m >>>> $1 \e[0m"
}

msg_fail() {
  echo -e "\e[31m >>>> $1 \e[0m"
}

run_shell() {
  # Hack to avoid job control error.
  # https://forums.gentoo.org/viewtopic-t-998098-start-0.html
	setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
}

msg_info "Mounting /proc..." 
mount -t proc proc /proc -o nosuid,noexec,nodev

msg_info "Mounting /sys..."
mount -t sysfs sys /sys -o nosuid,noexec,nodev

msg_info "Mounting /dev..."
mount -t devtmpfs dev /dev -o mode=0755,nosuid

msg_info "Mounting /run..."
mount -t tmpfs run /run -o nosuid,nodev,mode=0755

msg_info "Setting up network..."
udhcpc

msg_info "Waiting for system to catch up..."

sleep 5

while [ 1 ]; do
    dialog --menu "What do you want to do" 0 0 0 \
        shell           "Drop to shell" \
        reboot          "Reboot" \
        poweroff        "Shutdown" 2> /tmp/what_next
    clear
    
    case $(cat /tmp/what_next) in
        shell)
            run_shell
        ;;
        reboot)
            reboot -f
        ;;
        poweroff)
            poweroff -f
        ;;
    esac
done
